/**
 * Constants for the Custom Framework application.
 * <p /><p />
 * @author Raymundo Rodriguez
 */
public virtual class StaticVariablesClass_CF {

    //Custom framework variables.
    public static String CUSTOM_FRAMEWORK_EXAMPLE_1_NAME {get{return 'Ashton Cox';}}
    public static String CUSTOM_FRAMEWORK_EXAMPLE_1_POSITION {get{return 'Junior Technical Author';}}
    public static String CUSTOM_FRAMEWORK_EXAMPLE_1_OFFICE {get{return 'San Francisco';}}
    public static String CUSTOM_FRAMEWORK_EXAMPLE_1_SALARY {get{return '$86,000';}}
    public static String CUSTOM_FRAMEWORK_EXAMPLE_2_NAME {get{return 'Garrett Winters';}}
    public static String CUSTOM_FRAMEWORK_EXAMPLE_2_POSITION {get{return 'Accountant';}}
    public static String CUSTOM_FRAMEWORK_EXAMPLE_2_OFFICE {get{return 'Tokyo';}}
    public static String CUSTOM_FRAMEWORK_EXAMPLE_2_SALARY {get{return '$170,750';}}
    public static String CUSTOM_FRAMEWORK_EXAMPLE_3_NAME {get{return 'Tiger Nixon';}}
    public static String CUSTOM_FRAMEWORK_EXAMPLE_3_POSITION {get{return 'System Architect';}}
    public static String CUSTOM_FRAMEWORK_EXAMPLE_3_OFFICE {get{return 'Edinburgh';}}
    public static String CUSTOM_FRAMEWORK_EXAMPLE_3_SALARY {get{return '$320,800';}}
    public static String CUSTOM_FRAMEWORK_EXAMPLE_4_ALPHA_CODE {get{return '00001234';}}
    public static String CUSTOM_FRAMEWORK_EXAMPLE_4_POSITION {get{return 'System Architect';}}
    public static String CUSTOM_FRAMEWORK_EXAMPLE_5_ALPHA_CODE {get{return '12345';}}
    public static String CUSTOM_FRAMEWORK_EXAMPLE_5_POSITION {get{return 'Accountant';}}
    public static String CUSTOM_FRAMEWORK_EXAMPLE_6_ALPHA_CODE {get{return '999999';}}
    public static String CUSTOM_FRAMEWORK_EXAMPLE_6_POSITION {get{return 'Junior Technical Author';}}
    public static String CUSTOM_FRAMEWORK_EXAMPLE_7_ALPHA_CODE {get{return 'KAMRUL AHSAN - 3410989';}}
    public static String CUSTOM_FRAMEWORK_EXAMPLE_7_POSITION {get{return 'Senior Javascript Developer';}}
    public static String CUSTOM_FRAMEWORK_EXAMPLE_8_ALPHA_CODE {get{return 'ROBERT HUITZ - 1976132';}}
    public static String CUSTOM_FRAMEWORK_EXAMPLE_8_POSITION {get{return 'Accountant';}}
    public static String CUSTOM_FRAMEWORK_EXAMPLE_9_ALPHA_CODE {get{return '00000001';}}
    public static String CUSTOM_FRAMEWORK_EXAMPLE_9_POSITION {get{return 'Integration Specialist';}}
    public static String CUSTOM_FRAMEWORK_EXAMPLE_10_ALPHA_CODE {get{return '1';}}
    public static String CUSTOM_FRAMEWORK_EXAMPLE_10_POSITION {get{return 'Sales Assistant';}}
    public static String CUSTOM_FRAMEWORK_EXAMPLE_11_ALPHA_CODE {get{return 'KAMRUL AHSAN - 3510123';}}
    public static String CUSTOM_FRAMEWORK_EXAMPLE_11_POSITION {get{return 'Integration Specialist';}}
    public static String CUSTOM_FRAMEWORK_EXAMPLE_12_NAME {get{return 'test 1 - Name';}}
    public static String CUSTOM_FRAMEWORK_EXAMPLE_12_POSITION {get{return 'test 1 - Position';}}
    public static String CUSTOM_FRAMEWORK_EXAMPLE_12_OFFICE {get{return 'test 1 - Office';}}
    public static String CUSTOM_FRAMEWORK_EXAMPLE_12_SALARY {get{return 'test 1 - Salary';}}
    public static String CUSTOM_FRAMEWORK_EXAMPLE_13_NAME {get{return 'test 2 - Name';}}
    public static String CUSTOM_FRAMEWORK_EXAMPLE_13_POSITION {get{return 'test 2 - Position';}}
    public static String CUSTOM_FRAMEWORK_EXAMPLE_13_OFFICE {get{return 'test 2 - Office';}}
    public static String CUSTOM_FRAMEWORK_EXAMPLE_13_SALARY {get{return 'test 2 - Salary';}}
    public static String CUSTOM_FRAMEWORK_FATAL_MESSAGE {get{return 'Fatal message.';}}
    public static String CUSTOM_FRAMEWORK_SUCCESS_MESSAGE {get{return 'Success message.';}}
    public static String CUSTOM_FRAMEWORK_MEMBER_ID {get{return 'CustomFrameworkAccount';}}
    public static String CUSTOM_FRAMEWORK_ACCOUNT {get{return 'Account';}}
    public static String CUSTOM_FRAMEWORK_BILING_CITY {get{return 'TestCity';}}
    public static String CUSTOM_FRAMEWORK_GRAPHS {get{return 'GRAPHS';}}
    public static String CUSTOM_FRAMEWORK_ACCOUNT_RECORD_TYPE {get{return 'Business Account';}}
    
    //Lightning URL pieces.
    public static String CUSTOM_FRAMEWORK_LIGHTNING_URL_HTTPS {get{return 'https://';}}
    public static String CUSTOM_FRAMEWORK_LIGHTNING_URL_FORCE_ONE_APP {get{return '.lightning.force.com/one/one.app#/';}}
    public static String CUSTOM_FRAMEWORK_LIGHTNING_URL_C {get{return '--c.';}} 
    public static String CUSTOM_FRAMEWORK_LIGHTNING_URL_HTTPS_C_PREFIX {get{return 'https://c.';}}
    public static String CUSTOM_FRAMEWORK_LIGHTNING_URL_VISUAL_FORCE {get{return '.visual.force.com';}} 
    
    //General Constants
    public static String CUSTOM_FRAMEWORK_BLANK {get{return '';}} 
}